version: "3.5"

services:
    client:
#        image: amadeologcomex/vuejs-intranet
        build: .
        volumes:
            - ./:/app/
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm run serve
        networks:
            - intranet
        ports:
            - "8080:8080"

networks:
    intranet:
        driver: bridge
